const num1=10;
const num2=50;
// const total=num1+num2;
// console.log(total);
// const total=num1*num2;
// console.log(total);
// const total=num1/num2;
// console.log(total);
const total=num1%num2;
console.log(total);